//course


export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const UPDATE_USER_DETAIL_SUCCESS = "UPDATE_USER_DETAIL_SUCCESS";
export const GET_USER_SETTINGS_SUCCESS = "GET_USER_SETTINGS_SUCCESS";

export const GET_MY_CUSTOMERORDERS_SUCCESS = "GET_MY_CUSTOMERORDERS_SUCCESS";
export const GET_MY_BOOKMARKS_SUCCESS = "GET_MY_BOOKMARKS_SUCCESS";
export const GET_MY_CERTIFICATES_SUCCESS = "GET_MY_CERTIFICATES_SUCCESS";
export const GET_MY_PACKAGES_SUCCESS = "GET_MY_PACKAGES_SUCCESS";
export const GET_MY_COURSES_SUCCESS = "GET_MY_COURSES_SUCCESS";
export const GET_COURSES_AND_PACKAGES_SUCCESS =
  "GET_COURSES_AND_PACKAGES_SUCCESS";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_PACKAGE_SUCCESS = "GET_PACKAGE_SUCCESS";
export const GET_COURSE_PACKAGE_SUCCESS="GET_COURSE_PACKAGE_SUCCESS";
export const GET_COURSES_BY_INSTRUCTOR_SUCCESS =
  "GET_COURSES_BY_INSTRUCTOR_SUCCESS";
export const GET_CUSTOM_PACKAGE_SUCCESS = "GET_CUSTOM_PACKAGE_SUCCESS";
export const GET_RELATED_COURSES_SUCCESS = "GET_RELATED_COURSES_SUCCESS";
export const GET_RELATED_PACKAGES_SUCCESS = "GET_RELATED_PACKAGES_SUCCESS";
export const GET_COURSE_NO_USER_SUCCESS = "GET_COURSE_NO_USER_SUCCESS";
export const GET_ALL_CAT_SUBCAT_SUCCESS = "GET_ALL_CAT_SUBCAT_SUCCESS";
export const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
export const CHECKOUT_CREDIT_SUCCESS="CHECKOUT_CREDIT_SUCCESS";
export const CLEAR_CHECKOUT_SUCCESS="CLEAR_CHECKOUT_SUCCESS";
export const UPDATE_CHECKCOUT_SUCCESS="UPDATE_CHECKCOUT_SUCCESS";
export const CLEAR_UPDATE_CHECKCOUT_SUCCESS="CLEAR_UPDATE_CHECKCOUT_SUCCESS";

export const GET_MY_DASH_BOARD_SUCCESS="GET_MY_DASH_BOARD_SUCCESS";
export const REMOVE_BOOKMARK_SUCCESS="REMOVE_BOOKMARK_SUCCESS";
export const ADD_BOOKMARK_SUCCESS="ADD_BOOKMARK_SUCCESS";
export const GET_COURSES_AND_PACKAGES_BY_CATEGORY_SUCCESS="GET_COURSES_AND_PACKAGES_BY_CATEGORY_SUCCESS";
export const SUBMIT_ASSESS_SUCCESS="SUBMIT_ASSESS_SUCCESS";
export const CLEAR_ASSESSMENT_SUCCESS="CLEAR_ASSESSMENT_SUCCESS";
export const COURSE_RECEVIEW_SUCCESS="COURSE_RECEVIEW_SUCCESS"

export const GET_MY_TRANSACTIONS_SUCCESS="GET_MY_TRANSACTIONS_SUCCESS"

//event
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_PAST_EVENTS_SUCCESS = "GET_PAST_EVENTS_SUCCESS";
export const GET_PAST_EVENT_SUCCESS = "GET_PAST_EVENT_SUCCESS";
export const REGISTER_EVENT_SUCCESS = "REGISTER_EVENT_SUCCESS";

//blog
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";

//instructor
export const GET_INSTRUCTOR_INFO_SUCCESS = "GET_INSTRUCTOR_INFO_SUCCESS";
export const GET_INSTRUCTOR_WORK_DETIAL_SUCCESS =
  "GET_INSTRUCTOR_WORK_DETIAL_SUCCESS";
export const GET_INSTRUCTOR_EDUCATION_DETIAL_SUCCESS =
  "GET_INSTRUCTOR_EDUCATION_DETIAL_SUCCESS";
export const GET_INSTRUCTOR_CERTIFICATE_DETIAL_SUCCESS =
  "GET_INSTRUCTOR_CERTIFICATE_DETIAL_SUCCESS";

//user
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const RESET_MESSAGE_SUCCESS = "RESET_MESSAGE_SUCCESS";
export const GET_REVIEWS_SUCCESS = "GET_REVIEWS_SUCCESS";

//home
export const GET_HOME_LAYOUT_SUCCESS = "GET_HOME_LAYOUT_SUCCESS";
export const SUBSCRIBE_NEWSLETTER_SUCCESS = "SUBSCRIBE_NEWSLETTER_SUCCESS";
export const UNSUBSCRIBE_NEWSLETTER_SUCCESS = "UNSUBSCRIBE_NEWSLETTER_SUCCESS";

//resourse
export const SUBMIT_CONTACT_SUCCESS = "SUBMIT_CONTACT_SUCCESS";

//message
export const RESET_RESOURSE_MESSAGE_SUCCESS = "RESET_RESOURSE_MESSAGE_SUCCESS";

//cart
export const GET_CART_DATA = "GET_CART_DATA";
export const GET_CART_DATA_START = "GET_CART_DATA_START";
export const GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";
export const GET_GENERATE_COUPON_SUCCESS= "GET_GENERATE_COUPON_SUCCESS";
export const CLEAR_COUPON= "CLEAR_COUPON";

//auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
